config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  resources :daily_habits
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "daily_habits#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/daily_habit.rb
require 'csv'

class DailyHabit < ApplicationRecord
  def self.to_csv
    attributes = column_names - %w[created_at updated_at]

    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |habit|
        csv << attributes.map { |attr| habit.send(attr) }
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/daily_habits_controller.rb
class DailyHabitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_daily_habit, only: %i[ show edit update destroy ]

  # GET /daily_habits or /daily_habits.json
  def index
    @daily_habits = DailyHabit.all.order(date: :desc)
    # handle csv export
    respond_to do |format|
      format.html
      format.csv { send_data @daily_habits.to_csv, filename: "daily-habits-#{Date.today}.csv" }
    end
  end

  # GET /daily_habits/1 or /daily_habits/1.json
  def show
  end

  # GET /daily_habits/new
  def new
    @daily_habit = DailyHabit.new
  end

  # GET /daily_habits/1/edit
  def edit
  end

  # POST /daily_habits or /daily_habits.json
  def create
    @daily_habit = DailyHabit.new(daily_habit_params)

    respond_to do |format|
      if @daily_habit.save
        format.html { redirect_to daily_habit_url(@daily_habit), notice: "Daily habit was successfully created." }
        format.json { render :show, status: :created, location: @daily_habit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @daily_habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_habits/1 or /daily_habits/1.json
  def update
    respond_to do |format|
      if @daily_habit.update(daily_habit_params)
        format.html { redirect_to daily_habit_url(@daily_habit), notice: "Daily habit was successfully updated." }
        format.json { render :show, status: :ok, location: @daily_habit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @daily_habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_habits/1 or /daily_habits/1.json
  def destroy
    @daily_habit.destroy

    respond_to do |format|
      format.html { redirect_to daily_habits_url, notice: "Daily habit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_habit
      @daily_habit = DailyHabit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def daily_habit_params
      params.require(:daily_habit).permit(:date, :hours_slept, :breakfast, :lunch, :dinner, :morning_meds, :evening_meds, :exercise_minutes, :daily_steps, :mood, :energy)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_habits_helper.rb
module DailyHabitsHelper
end

app/views/daily_habits/_daily_habit.html.erb
<div id="<%= dom_id daily_habit %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Date:</strong>
    <%= daily_habit.date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Hours slept:</strong>
    <%= daily_habit.hours_slept %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Breakfast:</strong>
    <%= daily_habit.breakfast %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Lunch:</strong>
    <%= daily_habit.lunch %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Dinner:</strong>
    <%= daily_habit.dinner %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Morning meds:</strong>
    <%= daily_habit.morning_meds %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Evening meds:</strong>
    <%= daily_habit.evening_meds %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Exercise minutes:</strong>
    <%= daily_habit.exercise_minutes %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Daily steps:</strong>
    <%= daily_habit.daily_steps %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Mood:</strong>
    <%= daily_habit.mood %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Energy:</strong>
    <%= daily_habit.energy %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this entry", daily_habit, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this entry", edit_daily_habit_path(daily_habit), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/daily_habits/_form.html.erb
<%= form_with(model: daily_habit, class: "contents") do |form| %>
  <div class="border border-gray-300 rounded-md px-5 pb-5 mt-5 mb-10">
    <% if daily_habit.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(daily_habit.errors.count, "error") %> prohibited this daily_habit from being saved:</h2>

        <ul>
          <% daily_habit.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :date %>
      <%= form.date_field :date, value: @daily_habit.date || Date.today, class: "block shadow-white rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full bg-gray-700 text-white" %>
    </div>

    <div class="my-5">
      <%= form.label :hours_slept %>
      <%= form.number_field :hours_slept, min: 0, max: 24, step: 0.5, class: "block shadow-white rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full bg-gray-700 text-white" %>
    </div>

    <div class="flex content-evenly justify-evenly flex-col md:flex-row">
      <div class="my-5">
        <%= form.label :breakfast %>
        <%= form.check_box :breakfast, class: "block mt-2 h-5 w-5" %>
      </div>

      <div class="my-5">
        <%= form.label :lunch %>
        <%= form.check_box :lunch, class: "block mt-2 h-5 w-5" %>
      </div>

      <div class="my-5">
        <%= form.label :dinner %>
        <%= form.check_box :dinner, class: "block mt-2 h-5 w-5" %>
      </div>

      <div class="my-5">
        <%= form.label :morning_meds %>
        <%= form.check_box :morning_meds, class: "block mt-2 h-5 w-5" %>
      </div>

      <div class="my-5">
        <%= form.label :evening_meds %>
        <%= form.check_box :evening_meds, class: "block mt-2 h-5 w-5" %>
      </div>
    </div>

    <div class="my-5">
      <%= form.label :exercise_minutes %>
      <%= form.number_field :exercise_minutes, class: "block shadow-white rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full bg-gray-700 text-white" %>
    </div>

    <div class="my-5">
      <%= form.label :daily_steps %>
      <%= form.number_field :daily_steps, class: "block shadow-white rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full bg-gray-700 text-white" %>
    </div>

    <div class="my-5 flex flex-col">
      <%= form.label :mood %>
      <span id="moodValue"><%= @daily_habit.mood || 6 %></span> <!-- Default to 5 if no value is set -->
      <%= form.range_field :mood, min: 1, max: 10, class: "block shadow-white rounded-md outline-none mt-2 w-full", oninput: "updateMoodValue(this.value)" %>
    </div>

    <div class="my-5 flex flex-col">
      <%= form.label :energy %>
      <span id="energyValue"><%= @daily_habit.energy || 6 %></span> <!-- Default to 5 if no value is set -->
      <%= form.range_field :energy, min: 1, max: 10, class: "block shadow-white rounded-md outline-none mt-2 w-full", oninput: "updateEnergyValue(this.value)" %>
    </div>

    <div class=" flex flex-col md:flex-row justify-center gap-5 mt-10">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-orange-600 text-white inline-block font-medium cursor-pointer" %>
      <%= link_to "Back to daily habits", daily_habits_path, class: "rounded-lg py-3 px-5 bg-gray-600 inline-block font-medium text-center" %>
    </div>
  </div>
<% end %>
<script>
  function updateMoodValue(value) {
    document.getElementById('moodValue').textContent = value;
  }
  function updateEnergyValue(value) {
    document.getElementById('energyValue').textContent = value;
  }
</script>

app/views/daily_habits/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing daily habit</h1>

  <%= render "form", daily_habit: @daily_habit %>

  <%= link_to "Show this daily habit", @daily_habit, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to daily habits", daily_habits_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/daily_habits/index.html.erb
<%= evil_icons_sprite %>
<div class="w-full">
  <div class="flex justify-between items-center sm:flex-row flex-col gap-5">
    <h1 class="font-bold text-4xl">Daily habits</h1>
    <div class="flex gap-5">
      <%= link_to "New daily habit", new_daily_habit_path, class: "rounded-lg py-3 px-5 bg-orange-600 text-white block font-medium" %>
      <%# Download CSV %>
      <%= link_to "Download CSV", daily_habits_path(format: :csv), class: "rounded-lg py-3 px-5 bg-orange-600 text-white block font-medium" %>
    </div>
  </div>

  <%# Desktop Table %>
  <table class="min-w-full table-auto border-collapse border border-gray-300 mt-10 hidden lg:table">
    <thead>
      <tr>
        <th class="table--header">Date</th>
        <th class="table--header">Hours Slept</th>
        <th class="table--header">Breakfast</th>
        <th class="table--header">Lunch</th>
        <th class="table--header">Dinner</th>
        <th class="table--header">Morning Meds</th>
        <th class="table--header">Evening Meds</th>
        <th class="table--header">Exercise Minutes</th>
        <th class="table--header">Daily Steps</th>
        <th class="table--header">Mood</th>
        <th class="table--header">Energy</th>
        <th class="table--header">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @daily_habits.each do |daily_habit| %>
        <tr>
          <td class="table--body_row"><%= daily_habit.date %></td>
          <td class="table--body_row"><%= daily_habit.hours_slept %></td>
          <td class="table--body_row"><%= daily_habit.breakfast ? 'Yes' : 'No' %></td>
          <td class="table--body_row"><%= daily_habit.lunch ? 'Yes' : 'No' %></td>
          <td class="table--body_row"><%= daily_habit.dinner ? 'Yes' : 'No' %></td>
          <td class="table--body_row"><%= daily_habit.morning_meds ? 'Yes' : 'No' %></td>
          <td class="table--body_row"><%= daily_habit.evening_meds ? 'Yes' : 'No' %></td>
          <td class="table--body_row"><%= daily_habit.exercise_minutes %></td>
          <td class="table--body_row"><%= daily_habit.daily_steps %></td>
          <td class="table--body_row"><%= daily_habit.mood %></td>
          <td class="table--body_row"><%= daily_habit.energy %></td>
          <td class="table--body_row flex flex-row gap-1">
            <%= link_to evil_icon('ei-eye', size: :m), daily_habit, class: "rounded-md py-1 px-2 text-orange-400 text-white block font-medium text-center" %>
            <%= link_to evil_icon('ei-pencil', size: :m), edit_daily_habit_path(daily_habit), class: "rounded-md py-1 px-2 text-orange-400 text-white block font-medium text-center" %>
            <%= link_to evil_icon('ei-trash', size: :m), daily_habit, method: :delete, data: { confirm: 'Are you sure?' }, class: "rounded-md py-1 px-2 text-red-600 text-white block font-medium text-center" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%# Mobile Table %>
  <div class="lg:hidden mt-10">
    <% @daily_habits.each do |daily_habit| %>
      <div class="mb-4 p-4 border border-gray-300 rounded-md">
        <p><strong>Date:</strong> <%= daily_habit.date %></p>
        <p><strong>Hours Slept:</strong> <%= daily_habit.hours_slept %></p>
        <p><strong>Breakfast:</strong> <%= daily_habit.breakfast ? 'Yes' : 'No' %></p>
        <p><strong>Lunch:</strong> <%= daily_habit.lunch ? 'Yes' : 'No' %></p>
        <p><strong>Dinner:</strong> <%= daily_habit.dinner ? 'Yes' : 'No' %></p>
        <p><strong>Morning Meds:</strong> <%= daily_habit.morning_meds ? 'Yes' : 'No' %></p>
        <p><strong>Evening Meds:</strong> <%= daily_habit.evening_meds ? 'Yes' : 'No' %></p>
        <p><strong>Exercise Minutes:</strong> <%= daily_habit.exercise_minutes %></p>
        <p><strong>Daily Steps:</strong> <%= daily_habit.daily_steps %></p>
        <p><strong>Mood:</strong> <%= daily_habit.mood %></p>
        <p><strong>Energy:</strong> <%= daily_habit.energy %></p>
        <!-- ... add other fields ... -->

        <div class="mt-2 flex gap-2">
          <%= link_to 'Show', daily_habit, class: "rounded-md py-1 px-2 bg-orange-400 text-white font-medium text-center" %>
          <%= link_to 'Edit', edit_daily_habit_path(daily_habit), class: "rounded-md py-1 px-2 bg-orange-400 text-white font-medium text-center" %>
          <%= link_to 'Destroy', daily_habit, method: :delete, data: { confirm: 'Are you sure?' }, class: "rounded-md py-1 px-2 bg-red-600 text-white font-medium text-center" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/daily_habits/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New daily habit</h1>

  <%= render "form", daily_habit: @daily_habit %>

</div>

app/views/daily_habits/show.html.erb
<div class="mx-auto w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= link_to "Back to Daily Habits", daily_habits_path, class: "rounded-lg py-3 px-5 bg-gray-600 font-medium" %>


    <div class=" w-72 border-2 border-white rounded px-5 mt-10">
      <%= render @daily_habit %>
    </div>

    <div class="flex flex-row justify-between mb-20">
      <%= link_to "Edit this entry", edit_daily_habit_path(@daily_habit), class: "mt-2 inline-block text-center rounded-lg py-3 px-5 bg-orange-600 font-medium" %>
      <%# <div class="inline-block ml-2"> %>
      <%= button_to "Destroy this entry", daily_habit_path(@daily_habit), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-600 font-medium" %>
      <%# </div> %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="dark">
  <head>
    <title>DailyHabitsTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-800 text-white">
    <%# Make this prettier with stimulus and tailwind %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%#  %>
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <%# devise logout link is current user logged in %>
      <% if user_signed_in? %>
        <p>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-md mb-10" %>
        </p>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>